services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
