# Generated by Django 4.2.30 on 2026-09-17 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_course_tags_badges_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetag',
            name='icon',
            field=models.CharField(choices=[('📚', '📚 Книги'), ('💻', '💻 Програмування'), ('🔢', '🔢 Математика'), ('🌍', '🌍 Світ'), ('🎨', '🎨 Мистецтво'), ('🔬', '🔬 Наука')], default='📚', max_length=8, verbose_name='Іконка'),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='normalized_name',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальний бал'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('self_study', 'Самовивчення'), ('video', 'Відеоурок'), ('mixed', 'Змішаний'), ('live', 'Онлайн-зустріч'), ('practice', 'Практика')], default='self_study', max_length=20, verbose_name='Тип уроку'),
        ),
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_completions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Завершення курсу',
                'verbose_name_plural': 'Завершення курсів',
            },
        ),
        migrations.AddConstraint(
            model_name='coursecompletion',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_course_completion'),
        ),
    ]