# Generated by Django 4.2.30 on 2026-09-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_normalize_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'ordering': ['name'], 'verbose_name': 'Тег курсу', 'verbose_name_plural': 'Теги курсів'},
        ),
        migrations.AlterField(
            model_name='course',
            name='completion_badge_color',
            field=models.CharField(blank=True, default='#6c63ff', max_length=7, verbose_name='Колір бейджика'),
        ),
        migrations.AlterField(
            model_name='course',
            name='completion_badge_icon',
            field=models.CharField(blank=True, default='🏆', max_length=8, verbose_name='Емблема бейджика'),
        ),
        migrations.AlterField(
            model_name='course',
            name='completion_badge_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Назва бейджика'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.coursetag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва тегу'),
        ),
    ]