# Generated by Django 4.2.30 on 2026-09-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursetag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, help_text='Необов’язково. Додайте конспект, презентацію, архів або інший навчальний матеріал.', upload_to='lesson_materials/', verbose_name='Файл уроку'),
        ),
    ]